### ISSUE TITLE
Deciding on SPACE_SIZE and SPACE_CENTER

### ISSUE THREAD

**Issue by egeozsoy** [microsoft/voxelpose-pytorch#10]
I have a custom dataset that I want to apply voxelpose to. But there is no explanation for how the values SPACE_SIZE and SPACE_CENTER were selected for the 3 datasets, therefore it is not clear to me what to set them to for my custom dataset

**Comment by CHUNYUWANG** [comment]
It depends on the calibration results. The basic idea is to calculate a 3D bounding box which covers the whole motion space. Then SPACE_CENTER denotes the center coordinate of the box and SPACE_SIZE denotes the lengths of the box.

**Comment by egeozsoy** [comment]
I see thank you. In that case making this box a little bit bigger than it needs to be should not degrade the performance right?

**Comment by CHUNYUWANG** [comment]
That's right. But you may need to consider the size of each voxel (which depends on the box size and number of voxels) as that affects the quantization error.

**Comment by StephanPan** [comment]
hi, @egeozsoy .What's your trainsets and testsets? Your custom datasets or open-source datasets? Did you implement the cross-datasets evaluation.

**Comment by sudo-vinnie** [comment]
@egeozsoy   
@CHUNYUWANG

I am also facing the same issue with a custom datasets?
Could you guys make a simple explanation the details regarding the parameters for:


```
 MULTI_PERSON:
  SPACE_SIZE:
    - 12000.0
    - 12000.0
    - 20000
  SPACE_CENTER:
    - 3000.0
    - 4500.0
    - 1000.0
  INITIAL_CUBE_SIZE:
    - 80
    - 80
    - 20
#  MAX_PEOPLE_NUM: 1
  THRESHOLD: 0.3
PICT_STRUCT:
  GRID_SIZE:
    - 2000.0
    - 2000.0
    - 2000.0
  CUBE_SIZE:
    - 64
    - 64
    - 64
```
